trigger: 
- master
#- feature*

variables:
    buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    pool: default
      
    steps:
    - script: dotnet restore
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration Release'
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True     
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'
    condition: succeededOrFailed()
- stage: DeploytoProd
  jobs:
  - job: Deploy
    pool:      
        name: default
    steps:
     - task: DownloadBuildArtifacts@1
       inputs:
         buildType: 'current'
         downloadType: 'single'
         artifactName: 'drop'
         downloadPath: '$(System.ArtifactsDirectory)'
     - task: AzureWebApp@1
       inputs:
         azureSubscription: 'MasterConnection'
         appType: 'webApp'
         appName: 'demowebappws'
         package: '$(System.ArtifactsDirectory)/drop/*.zip'
         deploymentMethod: 'auto'